### ISSUE TITLE
讨论下 shell_utils.cpp 中的 result->IsUndefined() 函数

### ISSUE THREAD

**Issue by warjiang** [linxiaowu66/v8-demo#1]
本地跑 shell demo的时候， result->IsUndefined() 会 segmentation fault错误。看了下IsUndefined 函数实现部分：
![image](https://user-images.githubusercontent.com/6478745/71321133-685e8f80-24f0-11ea-9d50-456d4006863e.png)

默认情况下 我没有加V8_ENABLE_CHECKS这个变量，应该是跑到了QuickIsUndefined 函数里面，这种情况下检测居然会直接挂掉。
然后我在cmake 里面加了 V8_ENABLE_CHECKS  的定义，跑 FullIsUndefined 就可以正常运行。请问您有遇到过这种情况么？

**Comment by guopingxiao** [comment]
👍![image](https://user-images.githubusercontent.com/11886494/73648073-bce05780-46b7-11ea-9cd5-a4345d0cd297.png)

https://www.mail-archive.com/v8-dev@googlegroups.com/msg160052.html

**Comment by linxiaowu66** [comment]
都没注意看到还有留言 （😢）
